name: Terraform Plan

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  terraform-plan:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: us-east-1
      TF_WORKING_DIR: terraform
      TF_LOG: INFO
      TF_LOG_PATH: terraform.log

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::992382494504:role/github-oidc-role
          aws-region: ${{ env.AWS_REGION }}

      - name: recreate terraform.tfvars from secret
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: |
          cat <<'EOF' > terraform.tfvars
          ${{ vars.TF_VARS }}
          ${{secrets.DOCKER_HUB_PASSWORD}}
          ${{secrets.DOCKER_HUB_USERNAME}}
          EOF

      - name: setup db seret as env
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: 
        
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Format Check
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform fmt -check

      - name: Terraform Init
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform init -input=false

      - name: Terraform Validate
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform validate

      - name: Terraform Plan
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform plan -no-color -out=tfplan.binary
        # run: terraform plan 

      - name: Upload plan artifact
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan
          path: terraform/tfplan.binary
  